### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by JesseTG**
This pull request does the following:

- Neaten up the `qmake` files, primarily by sorting each instance of `SOURCES` and `HEADERS` alphabetically for readability.
- Adds `Examples`, `Tools`, and `Plugins` to the project hierarchy.
- Fix a few failing tests for `FileSetInfo` and `NamingPolicyFilter`
- Fix a crash caused in `Observer`

### CODE REVIEW

**Comment by CJCombrink** [comment]
Hi, just a quick question, did you do the sorting by hand or did you use some tool or process to do the sorting? 

> sorting each instance of SOURCES and HEADERS alphabetically for readability.

**Comment by JesseTG** [comment]
I used the Unix `sort` tool.

**Comment by JesseTG** [comment]
@JPNaude How does this PR look?  I can split it into multiple smaller ones if you want.

**Comment by JesseTG** [comment]
...you know, I'm just gonna do that anyway.

**Comment by JPNaude** [comment]
Hi JesseTG

Great thank you for the changes. I've reviewed it and will merge the pull request now.

Cheers,
Jaco

**Pull request merged**
